### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by sbeehre** [Zoidwaffle/sql-npc-teleporter#1]
Hi 

I tried this on the latest build of Azerothcore and it doesnt work any more it gives the following error when trying to import the sql

MySQL error #1054 - Unknown column in 'Field List'

thanks

simon

**Comment by Zoidwaffle** [comment]
Hi,

saying you run the "latest" build is not very useful. Please provide the actual commit hash to help me out.

I currently use https://github.com/azerothcore/azerothcore-wotlk/commit/c5400b301259e048cfb89d3e591bef565d51cec3 which is a very recent commit.

I just tried importing the SQL on a a clean world database - and it worked for me without errors. So I cannot confirm the issue.

I suggest you take a backup of your world database - create a new clean one, and try to re-import and see if the issue persists.

**Comment by sbeehre** [comment]
Hi Peter 

thanks for the reply how do you find out which commit you are using? i did the install 2 days ago and its a clean database... i will try again and let you know.

Simon

**Comment by sbeehre** [comment]
![portal](https://user-images.githubusercontent.com/54608391/107604226-53186780-6c94-11eb-80c2-20a9958d326f.JPG)
 Tried it again and this is what i see... AzerothCore rev. d902411171fe 2021-02-06 21:06:30

**Comment by Zoidwaffle** [comment]
Hm, what version of MySQL are you using? I'm running on a 5.7 related branch (MariaDB).

If you are running on MySQL 8 then that might be the reason (just guessing here).

**Comment by sbeehre** [comment]
ah ok i used the bash script to install AC and it uses mysql 8.0

**Comment by Zoidwaffle** [comment]
OK, well... If you can downgrade, then I suggest doing that. I'm not planning on going to MySQL8 anytime soon at least :)
