### ISSUE TITLE
[Suggestion] Starter Zones?

### ISSUE THREAD

**Issue by StraysFromPath** [Zoidwaffle/sql-npc-teleporter#2]
Hi. It'd be super cool if you added the eight 1-5 starter zones to this NPC as it solves the classic "my and my friends want to play diff races but they start on different continents" issue.

<3

**Comment by Zoidwaffle** [comment]
Hi, I kinda have that already... I made a special teleporter just for that - so one that stands very near the spawning point and then allows you to get teleported to any other zone.

I made mine so it's cross faction - which may or may not be what you want?

Anyway, I have to find the SQL and perhaps clean it up a bit, then I can share it. No promises, but I guess I could get around to it this coming week.

**Comment by Zoidwaffle** [comment]
OK, so, turns out I already kinda prepared everything... Just needed to commit and push.

Again, I think you get it as cross-faction, so an update might be to make that optional.

Let me know if it works for you!

**Comment by StraysFromPath** [comment]
> OK, so, turns out I already kinda prepared everything... Just needed to commit and push.
> 
> Again, I think you get it as cross-faction, so an update might be to make that optional.
> 
> Let me know if it works for you!

Hi! I ran the SQL and it ran with no errors but it would be ideal to split it into two NPCs for most cases IMO.

One Alliance and One Horde teleporter for starter zones for most servers otherwise it's baiting new lvl 1 players into getting killed by guards (and then hardlocked as the nearest graveyard is very far and guards will kill again before you can get back to the NPC to teleport out).

A first time wow player won't know which starter zones/races would represent instant death + permanent locking of a character.

**Comment by Zoidwaffle** [comment]
Just letting you know, I will split up the script a bit, to support non-cross-faction-servers.

**Comment by Zoidwaffle** [comment]
... and there we go.

Modify the SQL before importing if you want cross-faction, a different model or whatever :-)

**Comment by Zoidwaffle** [comment]
And closing.
